import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Fully auto-generated. The build pipeline writes content into docs/costops/
// from the CostOps repo; any folders added there show up here automatically.
const sidebars: SidebarsConfig = {
  costopsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
