import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  otakuverseSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', slug: '/otakuverse/getting-started' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'generated-index', slug: '/otakuverse/tutorials' },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
  ],
};

export default sidebars;
