import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Fully auto-generated. The build pipeline writes content into docs/otakuverse/
// from the OtakuVerse repo; any folders added there show up here automatically.
const sidebars: SidebarsConfig = {
  otakuverseSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
